version: '3'
services:
    
  windows:
    container_name: windows-box
    image: "windows:servercore"

  web:
    container_name: webapp-frontend
    build: .
    ports:
      - "5000:5000"
  redis:
    container_name: redis-backend
    image: "redis:alpine"
